### PR TITLE
dockerfile based on devuan 4.0 chimaera

### PR DESCRIPTION
**Pull request by jaromil**
makes it easy to try on systems with an older python3 version

### CODE REVIEW

**Comment by alenpaulvarghese** [comment]
There are so many dependencies that are not included in this Dockerfile,
I will dockerize this project later. Thank you for this pull request :+1: .

**Comment by jaromil** [comment]
do you mind listing the dependencies somewhere?
are there more than those in the documentation and in the requirements.txt file?

**Comment by alenpaulvarghese** [comment]
> do you mind listing the dependencies somewhere?
> are there more than those in the documentation and in the requirements.txt file?

I was planning to release the next version of this project. The current render speed is very low ( Due to the fact that new browsers are spawned every time a discrete request arrives. ) so I hope to fix this in the next update, this will completely change the current dependencies. 

The plan is to dockerize the next version which will arrive soon ( currently facing college exams ).

**Comment by jaromil** [comment]
Cheers. Speed seems very OK for an on-site dedicated installation already. Break a leg for the exams.

**Pull request closed without merging**
