### PR TITLE
Added `.deepsource.toml`

### PR DESCRIPTION
**Pull request by fayasnoushad**
Added `.deepsource.toml` file for avoiding deepsource error.

### CODE REVIEW

**Comment by alenpaulvarghese** [comment]
Decided not to use deepsource.io  👍🏼

**Comment by fayasnoushad** [comment]
Aa, then remove deepsource.

**Comment by alenpaulvarghese** [comment]
removed 👍😅

**Comment by fayasnoushad** [comment]
Ok, Closing this pull request.

**Pull request closed without merging**
